[tool.poetry]
name = "nge"
version = "0.1.0"
description = ""
authors = ["liammccall <liamkm895@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = ">=5.0"
requests = ">=2.31"
llama-cpp-python = "^0.3.20"
yfinance = "^1.3.0"
pandas = "^3.0.2"
numpy = "^2.4.4"
backtesting = "^0.6.5"
scikit-learn = "^1.8.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
